#!/bin/bash
mkd(){ mkdir "$1" && cd "$1" ; }

alias c=clear

alias ll="ls -al"

alias gp=git_push

alias b=betty
alias pc="pycodestyle --first"

export PATH=$PWD:$PATH

alias upgrade="sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove && clear && echo 'upgrade done'"
